# Generated by Django 6.0.3 on 2026-04-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferrovelho_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(default='Geral', max_length=50),
        ),
    ]
