# Generated by Django 6.0.3 on 2026-04-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferrovelho_app', '0002_material_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('FINO', 'Fino'), ('PESADO', 'Pesado'), ('NAO_FERROSO', 'Não-Ferroso')], default='FINO', max_length=20),
        ),
    ]
