# Generated by Django 6.0.3 on 2026-04-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferrovelho_app', '0003_alter_material_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='tipo',
        ),
        migrations.AddField(
            model_name='material',
            name='categoria',
            field=models.CharField(choices=[('Fino', 'Fino'), ('Sucata', 'Sucata'), ('Outro', 'Outro')], default='Fino', max_length=20),
        ),
    ]
