# Generated by Django 6.0.3 on 2026-04-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferrovelho_app', '0004_remove_material_tipo_material_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
